DOSSEG
.MODEL SMALL
.STACK 100H

.DATA
CADENA    DB 'El 4 de febrero de 2022, a las 18:00 horas, tendremos el examen de Fundamentos de Computadores$'
CADENA2   DB 'NUMERO DE CONSONANTES: $'
CADENA3   DB 'FRECUENCIA DE CADA VOCAL: $'
CADENA4   DB 'TOTAL DE NUMEROS PARES: $'
NLINEA    DB 10D, 13D, '$'                                                                                        ; NUEVA LINEA
TOT_CONSO DB 0
TOT_PARES DB 0
TOT_A     DB 0
TOT_E     DB 0
TOT_I     DB 0
TOT_O     DB 0
TOT_U     DB 0

.CODE
MAIN PROC FAR
    MOV AX, @DATA ; LEER LA DIRECCION DEL SEGMENTO DE DATOS
    MOV DS, AX    ; Y GUARDARLA EN EL REGISTRO DE DATOS
    
    MOV SI, 0     ; 0 EN EL CONTADOR DE CADENA DE CARACTERES

CHECKALFANUM:
    CMP CADENA[SI], 30H ; CHEQUEO LOS NUMEROS PARES
    JE CONTARPARES
    CMP CADENA[SI], 32H
    JE CONTARPARES
    CMP CADENA[SI], 34H
    JE CONTARPARES
    CMP CADENA[SI], 36H
    JE CONTARPARES
    CMP CADENA[SI], 38H
    JE CONTARPARES
    CMP CADENA[SI], 'a' ; MAYOR O IGUAL A 'a'
    JAE CHECKMINUS
    CMP CADENA[SI], 'A' ; MAYOR O IGUAL A 'A'
    JAE CHECKMAYUS
    JMP CHECKDOLLARSIGN

CONTARPARES:
    INC TOT_PARES
    JMP CHECKDOLLARSIGN

CHECKMINUS:
    CMP CADENA[SI], 'z' ; MENOR O IGUAL A 'z'
    JBE CHECKVOCALMINUS
    JMP CHECKDOLLARSIGN

CHECKMAYUS:
    CMP CADENA[SI], 'Z' ; MENOR O IGUAL A 'Z'
    JBE CHECKVOCALMAYUS
    JMP CHECKDOLLARSIGN

CHECKDOLLARSIGN:
    INC SI
    CMP CADENA[SI], '$' ; COMPARO CON EL FIN DE LA CADENA
    JE SALIR            ; JUMP A SALIR SI ES EQUIVALENTE
    LOOP CHECKALFANUM   ; VUELVO AL LOOP INICIAL

CHECKVOCALMINUS:        ; CHEQUEO VOCALES MINUSCULAS
    CMP CADENA[SI], 'a'
    JZ CONTARVOCAL_A
    CMP CADENA[SI], 'e'
    JZ CONTARVOCAL_E
    CMP CADENA[SI], 'i'
    JZ CONTARVOCAL_I
    CMP CADENA[SI], 'o'
    JZ CONTARVOCAL_O
    CMP CADENA[SI], 'u'
    JZ CONTARVOCAL_U
    JMP CONTARCONS

CHECKVOCALMAYUS:        ; CHEQUEO VOCALES MAYUSCULAS
    CMP CADENA[SI], 'A'
    JZ CONTARVOCAL_A
    CMP CADENA[SI], 'E'
    JZ CONTARVOCAL_E
    CMP CADENA[SI], 'I'
    JZ CONTARVOCAL_I
    CMP CADENA[SI], 'O'
    JZ CONTARVOCAL_O
    CMP CADENA[SI], 'U'
    JZ CONTARVOCAL_U
    JMP CONTARCONS

CONTARVOCAL_A:
    INC TOT_A
    JMP CHECKDOLLARSIGN

CONTARVOCAL_E:
    INC TOT_E
    JMP CHECKDOLLARSIGN

CONTARVOCAL_I:
    INC TOT_I
    JMP CHECKDOLLARSIGN

CONTARVOCAL_O:
    INC TOT_O
    JMP CHECKDOLLARSIGN

CONTARVOCAL_U:
    INC TOT_U
    JMP CHECKDOLLARSIGN

CONTARCONS:
    INC TOT_CONSO
    JMP CHECKDOLLARSIGN

SALIR:
    MOV DX, OFFSET CADENA2
    MOV AH, 9
    INT 21H

    MOV CL, TOT_CONSO       ; PRINT CONSONANTES
    CALL PRINT

    MOV DX, OFFSET NLINEA
    MOV AH, 9
    INT 21H

    MOV DX, OFFSET CADENA3
    MOV AH, 9
    INT 21H

    MOV DL, 'A'             ; PRINT CANTIDAD DE 'A'
    MOV AH, 2
    INT 21H
    CALL PRINTCOLON
    MOV CL, TOT_A
    CALL PRINT

    CALL PRINTSPACE

    MOV DL, 'E'             ; PRINT CANTIDAD DE 'E'
    MOV AH, 2
    INT 21H
    CALL PRINTCOLON
    MOV CL, TOT_E
    CALL PRINT

    CALL PRINTSPACE

    MOV DL, 'I'             ; PRINT CANTIDAD DE 'I'
    MOV AH, 2
    INT 21H
    CALL PRINTCOLON
    MOV CL, TOT_I
    CALL PRINT

    CALL PRINTSPACE

    MOV DL, 'O'             ; PRINT CANTIDAD DE 'O'
    MOV AH, 2
    INT 21H
    CALL PRINTCOLON
    MOV CL, TOT_O
    CALL PRINT

    CALL PRINTSPACE

    MOV DL, 'U'             ; PRINT CANTIDAD DE 'U'
    MOV AH, 2
    INT 21H
    CALL PRINTCOLON
    MOV CL, TOT_U
    CALL PRINT

    MOV DX, OFFSET NLINEA
    MOV AH, 9
    INT 21H

    MOV DX, OFFSET CADENA4
    MOV AH, 9
    INT 21H

    MOV CL, TOT_PARES     ; PRINT CANTIDAD DE PARES
    CALL PRINT

    ; EJEMPLO DE OUTPUT:
    ; NUMERO DE CONSONANTES: 38
    ; FRECUENCIA DE CADA VOCAL: A:6 E:14 I:0 O:6 U:2
    ; TOTAL DE NUMEROS PARES: 8

    MOV AH, 76 ; VOLVER A DOS
    INT 21H
MAIN ENDP

PRINTSPACE PROC ; RUTINA PARA IMPRIMIR UN ESPACIO EN BLANCO
    MOV DL, ' '
    MOV AH, 2
    INT 21H
    RET
PRINTSPACE ENDP

PRINTCOLON PROC ; RUTINA PARA IMPRIMIR ':'
    MOV DL, 3AH
    MOV AH, 2
    INT 21H
    RET
PRINTCOLON ENDP

PRINT PROC            ; RUTINA PARA IMPRIMIR NUMEROS, SEAN UNIDADES/DECENAS/CENTENAS
    CMP CL, 10        ; COMPARO CON 10, SI ES MENOR IMPRIMO 1 DIGITO
    JB  UN_DIGITO
  
    CMP CL, 100       ; COMPARO CON 100, SI ES MENOR IMPRIMO 2 DIGITOS
    JB  DOS_DIGITOS
  
                      ; SI EL NUMERO NO ERA MENOR A 100, ES DE 3 CIFRAS
    MOV AL, CL        ; DIVIDO EL NUMERO (EN CL) POR 100
    XOR AH, AH
    MOV CH, 100
    DIV CH
  
    MOV BL, AL        ; ASIGNO EL COCIENTE A BL
    MOV CL, AH        ; ASIGNO EL RESTO A CL
  
    OR  BL, 30H       ; CONVIERTO BL A ASCII PARA EL OUTPUT
    MOV DL, BL
    MOV AH, 2
    INT 21H

  DOS_DIGITOS:
    MOV AL, CL        ; DIVIDO CL POR 10
    XOR AH, AH
    MOV CH, 10
    DIV CH

    MOV BL, AL        ; ASIGNO EL COCIENTE A BL
    MOV CL, AH        ; ASIGNO EL RESTO A CL

    OR  BL, 30H       ; CONVIERTO BL A ASCII PARA EL OUTPUT
    MOV DL, BL
    MOV AH, 2         ; STD OUTPUT
    INT 21H

  UN_DIGITO:          ; MUESTRA SOLO 1 DIGITO
    OR  CL, 30H       ; CL A ASCII PARA EL OUTPUT
    MOV DL, CL 
    MOV AH, 2         ; STD OUTPUT
    INT 21H
    
    RET               ; RETORNO AL CALL
PRINT ENDP

END MAIN
