DOSSEG
.MODEL SMALL
.STACK 100H

.DATA
CADENA    DB 'El 4 de febrero de 2022, a las 18:00 horas, tendremos el examen de Fundamentos de Computadores$'
CADENA2   DB 'NUMERO DE CONSONANTES: $'
CADENA3   DB 'FRECUENCIA DE CADA VOCAL: $'
CADENA4   DB 'TOTAL DE NUMEROS PARES: $'
NLINEA    DB 10D, 13D, '$'                                                                                        ; NUEVA LINEA
TOT_CONSO DB 30H ; Inicializo en '0' (30H)
TOT_PARES DB 30H
TOT_A     DB 30H
TOT_E     DB 30H
TOT_I     DB 30H
TOT_O     DB 30H
TOT_U     DB 30H

.CODE
MAIN PROC FAR
    MOV AX, @DATA ; LEER LA DIRECCION DEL SEGMENTO DE DATOS
    MOV DS, AX ; Y GUARDARLA EN EL REGISTRO DE DATOS
    
    ; COMPLETAR AQUI PARA ANALIZAR LA CADENA DE CARACTERES CADENA
    MOV SI, 0 ; 0 en el contador de cadena de caracteres

CHECKALFANUM:
    CMP CADENA[SI], '0' ; 0
    JZ CONTARPARES
    CMP CADENA[SI], '2' ; 2
    JZ CONTARPARES
    CMP CADENA[SI], '4' ; 4
    JZ CONTARPARES
    CMP CADENA[SI], '6' ; 6
    JZ CONTARPARES
    CMP CADENA[SI], '8' ; 8
    JZ CONTARPARES
    CMP CADENA[SI], 'a' ; Mayor o igual a 'a' o 61H
    JAE CHECKMINUS
    CMP CADENA[SI], 'A' ; Mayor o igual a 'A' o 41H
    JAE CHECKMAYUS
    JMP CHECKDOLLARSIGN

CONTARPARES:
    INC TOT_PARES
    JMP CHECKDOLLARSIGN

CHECKMINUS:
    CMP CADENA[SI], 'z' ; Menor o igual a 'z' o 7AH
    JBE CHECKVOCALMINUS
    JMP CHECKDOLLARSIGN

CHECKMAYUS:
    CMP CADENA[SI], 'Z' ; Menor o igual a 'Z' o 5AH
    JBE CHECKVOCALMAYUS
    JMP CHECKDOLLARSIGN

CHECKDOLLARSIGN:
    INC SI
    CMP CADENA[SI], '$' ; COMPARO CON EL FIN DE LA CADENA
    JZ SALIR
    LOOP CHECKALFANUM

CHECKVOCALMINUS:        ; Chequeo por cada vocal minuscula
    CMP CADENA[SI], 'a'
    JZ CONTARVOCAL_A
    CMP CADENA[SI], 'e'
    JZ CONTARVOCAL_E
    CMP CADENA[SI], 'i'
    JZ CONTARVOCAL_I
    CMP CADENA[SI], 'o'
    JZ CONTARVOCAL_O
    CMP CADENA[SI], 'u'
    JZ CONTARVOCAL_U
    JMP CONTARCONS

CHECKVOCALMAYUS:        ; Chequeo por cada vocal mayuscula
    CMP CADENA[SI], 'A'
    JZ CONTARVOCAL_A
    CMP CADENA[SI], 'E'
    JZ CONTARVOCAL_E
    CMP CADENA[SI], 'I'
    JZ CONTARVOCAL_I
    CMP CADENA[SI], 'O'
    JZ CONTARVOCAL_O
    CMP CADENA[SI], 'U'
    JZ CONTARVOCAL_U
    JMP CONTARCONS

CONTARVOCAL_A:
    INC TOT_A
    JMP CHECKDOLLARSIGN

CONTARVOCAL_E:
    INC TOT_E
    JMP CHECKDOLLARSIGN

CONTARVOCAL_I:
    INC TOT_I
    JMP CHECKDOLLARSIGN

CONTARVOCAL_O:
    INC TOT_O
    JMP CHECKDOLLARSIGN

CONTARVOCAL_U:
    INC TOT_U
    JMP CHECKDOLLARSIGN

CONTARCONS:
    INC TOT_CONSO
    JMP CHECKDOLLARSIGN

SALIR:
    MOV DX, OFFSET CADENA2
    MOV AH, 9
    INT 21H

    XOR AX, AX
    MOV AX, TOT_CONSO
    CALL PRINT

    MOV DX, OFFSET NLINEA
    MOV AH, 9
    INT 21H

    MOV DX, OFFSET CADENA3
    MOV AH, 9
    INT 21H

    MOV DL, 'A'
    MOV AH, 2
    INT 21H
    CALL PRINTCOLON
    MOV DL, TOT_A
    MOV AH, 2
    INT 21H

    CALL PRINTSPACE
    MOV DL, 'E'
    MOV AH, 2
    INT 21H
    CALL PRINTCOLON
    XOR AX, AX
    MOV AX, TOT_E
    CALL PRINT
    XOR AX, AX

    CALL PRINTSPACE
    MOV DL, 'I'
    MOV AH, 2
    INT 21H
    CALL PRINTCOLON
    MOV DL, TOT_I
    MOV AH, 2
    INT 21H

    CALL PRINTSPACE
    MOV DL, 'O'
    MOV AH, 2
    INT 21H
    CALL PRINTCOLON
    MOV DL, TOT_O
    MOV AH, 2
    INT 21H

    CALL PRINTSPACE
    MOV DL, 'U'
    MOV AH, 2
    INT 21H
    CALL PRINTCOLON
    MOV DL, TOT_U
    MOV AH, 2
    INT 21H

    MOV DX, OFFSET NLINEA
    MOV AH, 9
    INT 21H

    MOV DX, OFFSET CADENA4
    MOV AH, 9
    INT 21H

    MOV DL, TOT_PARES
    MOV AH, 2
    INT 21H
    
    MOV AH, 76 ; VOLVER A DOS
    INT 21H
MAIN ENDP

PRINTSPACE PROC
    MOV DL, ' '
    MOV AH, 2
    INT 21H
    RET
PRINTSPACE ENDP

PRINTCOLON PROC
    MOV DL, 3AH
    MOV AH, 2
    INT 21H
    RET
PRINTCOLON ENDP

PRINT PROC
    XOR CX, CX ; INICIALIZO CONTADORES
    XOR DX, DX

    LABEL1:
        CMP AX, 0 ; AX == 0 ?
        JE PRINT1
         
        MOV BX, 10
        DIV BX      ; EXTRAIGO ULTIMO DIGITO
        PUSH DX     ; PUSH AL STACK
        INC CX      ; INCREMENTO EL CONTEO
        XOR DX, DX  ; DX = 0
        JMP LABEL1

    PRINT1:
        CMP CX, 0   ; CHEQUEO SI ES > 0
        JE EXIT
        POP DX      ; EXTRAIGO EL TOP DEL STACK
        ADD DX, 48  ; 48 = REPRESENTACION DE 2 DIGITOS EN ASCII
        MOV AH, 2   ; PRINT
        INT 21H
        DEC CX      ; DECREMENTO
        JMP PRINT1

    EXIT:
        RET
PRINT ENDP

END MAIN
